version: "2"
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - errorlint
    - exhaustive
    - exptostd
    - forbidigo
    - gocritic
    - godox
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nilnesserr
    - nolintlint
    - perfsprint
    - predeclared
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: sync/atomic
              desc: Use go.uber.org/atomic instead of sync/atomic
            - pkg: github.com/stretchr/testify/assert
              desc: Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
            - pkg: github.com/pkg/errors
              desc: Use 'errors' or 'fmt' instead of github.com/pkg/errors
            - pkg: gzip
              desc: Use github.com/klauspost/compress instead of gzip
            - pkg: zlib
              desc: Use github.com/klauspost/compress instead of zlib
    forbidigo:
      forbid:
        - pattern: time.Sleep
          msg: Please use require.Eventually or assert.Eventually instead unless you've no other option
        - pattern: ^time\.After$
          msg: time.After may leak resources. Use time.NewTimer instead.
    godox:
      keywords:
        - FIXME
    revive:
      confidence: 0.8
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: empty-lines
          disabled: true
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: function-length
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: string-format
          disabled: true
        - name: unexported-naming
          disabled: true
        - name: unexported-return
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: empty-block
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 25
        - name: cyclomatic
          arguments:
            - 25
        - name: function-result-limit
          arguments:
            - 5
        - name: unhandled-error
          arguments:
            - fmt.*
            - bytes.Buffer.*
            - strings.Builder.*
    testifylint:
      enable-all: true
      disable:
        - float-compare
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path-except: _test\.go|tests/.+\.go
        text: time.Sleep
      - linters:
          - revive
        path: _test\.go|tests/.+\.go
        text: (cyclomatic|cognitive)
      - linters:
          - revive
        path: _test\.go|tests/.+\.go
        text: (dot-imports|unchecked-type-assertion)
    paths:
      - ^proto
      - ^.git
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/PlayerNeo42/gredis
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - ^proto
      - ^.git
      - third_party$
      - builtin$
      - examples$
