version: 2

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - main: ./cmd/server
    id: "gvalkey"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

# dockers:
#   - image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
#     goos: linux
#     goarch: amd64
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#       - "--label=org.opencontainers.image.source={{ .GitURL }}"
#       - "--label=org.opencontainers.image.version={{ .Version }}"
#       - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#       - "--label=org.opencontainers.image.created={{ .Date }}"

#   - image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
#     goos: linux
#     goarch: arm64
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/arm64"
#       - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#       - "--label=org.opencontainers.image.source={{ .GitURL }}"
#       - "--label=org.opencontainers.image.version={{ .Version }}"
#       - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#       - "--label=org.opencontainers.image.created={{ .Date }}"

# docker_manifests:
#   - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}"
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
#   - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^doc:"
      - "^test:"
      - "^ci:"
# release:
#   footer: >-

#     ---

#     Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
